#!/bin/bash
: '
    Print leaf file/directory from a given path

                    Author: Viki (a) Vignesh Natarajan
                    Firma : vikilabs.org 

'

source ./fnc_exit_on_command_failure.sh
source ./fnc_string_helper.sh

function get_leaf_from_path() ##arg1 - "full path"
{  
    is_string_empty $1
    exit_on_command_failure $LINENO
    
    main_string=$1
    prefix="*/"
    output=${main_string##$prefix}
    echo $output
}

function usage()
{
    echo "Usage: "
    echo ""
    echo "      get_leaf_from_path \"full_path\""
    echo ""
    echo ""
    echo "Example: "
    echo ""
    echo "      get_leaf_from_path \"/home/test/file.jpg\""
    echo ""
    echo "This command will print the leaf file/directory -> file.jpg"
    echo ""
    echo ""
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

if [ -z "$1" ]; then
    echo
    echo "Error: argument 1 is empty"
    echo
    usage
    exit 1
fi

get_leaf_from_path "$1"
